version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings

      - name : hosts
        identifier: raw_hosts

      - name : raw_reviews
        identifier: raw_reviews
